### PR TITLE
passing more files through gjslint

### PR DESCRIPTION
**Pull request by heychirag**
Almost all the files are lintfree now.

@Kolpa, would you mind adding docs for [datePatch.js](https://github.com/OiWorld/CarbonFootprintGoogleMaps/blob/master/Source/pages/js/datePatch.js)?

### CODE REVIEW

**Comment by Ceilican** [comment]
Thank you!

**Comment by heychirag** [comment]
@Ceilican, should I resolve the conflicts?

**Comment by Ceilican** [comment]
> @Ceilican, should I resolve the conflicts?

Yes, please!  (Did I accidentally merge @Kolpa 's datePatch PR before this one? If so, sorry!)

**Comment by heychirag** [comment]
no problem. Done!

**Comment by Ceilican** [comment]
Many thanks!

**Pull request merged**
