### PR TITLE
public transport emssions for heremaps

### PR DESCRIPTION
**Pull request by heychirag**
Hi @Ceilican,

After Prateek fixed the map managers in his last PR, I tried adding support for displaying of public transport emission for remaining map managers. I have added support for HereMaps but however, I wasn't able to do this for MapQuest and OpenStreet maps since I wasn't able to get any transit info on my system. They do provide it for some cities though. I tried searching for routes in these cities but to no avail. Even using VPN to mock my location turned out to be a futile attempt.

[This](http://wiki.openstreetmap.org/wiki/Public_transport#Public_transports_by_country) page shows that transit routes are available for Germany for OpenStreet maps and maybe for MapQuest too. So I will have to bother @Kolpa to get this done.

### CODE REVIEW

**Comment by Ceilican** [comment]
Thanks!

**Comment by Ceilican** [comment]
> After Prateek fixed the map managers in his last PR, I tried adding support for displaying of public transport emission for remaining map managers. I have added support for HereMaps but however, I wasn't able to do this for MapQuest and OpenStreet maps since I wasn't able to get any transit info on my system. They do provide it for some cities though. I tried searching for routes in these cities but to no avail. Even using VPN to mock my location turned out to be a futile attempt. This page shows that transit routes are available for Germany for OpenStreet maps and maybe for MapQuest too. So I will have to bother @Kolpa to get this done.

This is strange. Does this mean that MapQuest and OSM detect that you are not in Germany and, therefore, refuse to show you transit information?

**Comment by heychirag** [comment]
This was probably because chrome's location service doesn't rely on IP address and hence was able to find my true location. I don't exactly know why they refused to show me transit information.

**Comment by Kolpa** [comment]
So i have looked into OSM and MapQuest and have not found any way of getting a public transit route from their service not on mobile or on desktop inside of Germany. So i guess this does not seem possible.

**Comment by Ceilican** [comment]
Ok. Thanks to both of you for investigating this.
If it is impossible, then let's move on.

**Pull request merged**
