### PR TITLE
fixed Google Maps manager

### PR DESCRIPTION
**Pull request by heychirag**
My last PR had broken down the functionality for Google Maps. So it wasn't working on any browser. Sorry for this.

Could you share with me the screenshots of the **popup** and **options page** on Safari? I would like to make sure that its working fine on a retina display as well.

### CODE REVIEW

**Comment by Ceilican** [comment]
screen shot 2016-08-21 at 18 42 30
screen shot 2016-08-21 at 18 42 45

**Comment by Ceilican** [comment]
Thanks!

**Comment by heychirag** [comment]
Thanks for sharing the screenshots. The globe does look a bit pixelated in the popup on a retina display. Should we replace it with a higher resolution version?

**Comment by Ceilican** [comment]
Indeed. I hadn't noticed that. Using a higher resolution version would be a good idea.

**Pull request merged**
