### PR TITLE
Fixing the build system and adding support for firefox builds

### PR DESCRIPTION
**Pull request by Kolpa**
This commit introduces a lot of stuff but the core points are

- support for bundling the extension via a simple gulp command
- adding support for firefox as a browser platform

Right now there is still a problem with firefox compatibility inside of the options.js file which needs to be discussed with everyone since it concerns the way we implement code to be non browser specific, i have added a [todo](https://github.com/OiWorld/CarbonFootprintGoogleMaps/commit/5ba2ddb7bf611c558f0fddb9503364592531c85e#commitcomment-18574882) to the concerning line and would like to discuss how we can fix this.

### CODE REVIEW

**Comment by Ceilican** [comment]
Thanks, @Kolpa . There are conflicts that prevent automatic merging of this PR. Could you solve the conflicts?

**Comment by Ceilican** [comment]
> Right now there is still a problem with firefox compatibility inside of the options.js file which needs to be discussed with everyone since it concerns the way we implement code to be non browser specific, i have added a todo to the concerning line and would like to discuss how we can fix this.

Ok. Could you try to discuss this among yourselves first? If you don't find a satisfactory solution, please let me know and then I can help. In any case, please keep me informed about the conceived solution.

**Comment by Kolpa** [comment]
okay everything should be mergeable now and the bugs and problems with options.js should be resolved!

**Comment by Ceilican** [comment]
Thanks!

**Pull request merged**
