### PR TITLE
Rewritten version of the carbon Footprints project and the base for all further work

### PR DESCRIPTION
**Pull request by Kolpa**

### CODE REVIEW

**Comment by Ceilican** [comment]
Hi Kolya! This pull request has conflicts that prevent me from automatically merging it in github. Could you make it automatically mergeable?
Thanks in advance!

**Comment by PrateekGupta1509** [comment]
Hi bruno,

I am making a little more tweaks in the kolya's repo again. So we will send
it by tomorrow with the revised part which can be directly merged as well.

Regards,
Prateek

**Comment by Ceilican** [comment]
Great! Many thanks!

**Comment by Kolpa** [comment]
Okay so after a lot of sweating and maybe some desperation i managed to get this to merge without conflicts :sweat_smile:
the travis build seems to be failing because there is no .travis.yml but i could not find one on master either so i guess it has not been setup yet?

**Comment by Ceilican** [comment]
Many thanks, Kolya!

> the travis build seems to be failing because there is no .travis.yml but i could not find one on master either so i guess it has not been setup yet?

That is correct! One has to be created.

@Kolpa , @PrateekGupta1509 and @heychirag , who of you would like to create the travis.yml file?

**Pull request merged**
