### PR TITLE
Redesigned Options Page UI

### PR DESCRIPTION
**Pull request by heychirag**
In this Pull Request, I have:

1. Enhanced and Simplified options page UI
2. Added currency selection
3. Improved form Validation
4. Changed units for sake of simplicity

### CODE REVIEW

**Comment by Ceilican** [comment]
Hi @heychirag ! Could you post here a screenshot of the new options pages?

**Comment by heychirag** [comment]
Hi @Ceilican 

screen shot 2016-06-06 at 5 04 07 pm

**Comment by Ceilican** [comment]
Thanks! 

At first your redesign looked a bit counter-intuitive to me, but now I see its point. Well-done!

Here are some minor suggestions for improvement:

1) The fuel type is only relevant when the user is inputing fuel efficiency/consumption. Therefore, the fuel type should be below the first question.

2) I think it is better to swap the two questions/options. Inputting CO2 emission rate should be above. Inputting fuel efficiency/consumption should be below.

3) I think "US Customary" is usually called "Imperial" unit system. Could you please check this?

4) There is potential for making the UI more minimalistic by removing the questions. For example, instead of "[ ] Know your vehicle's average CO2 emission?  CO2 Emissions: 2.72 kg/km", we could have simply "[ ] Your vehicle's average CO2 emission rate: 2.72 kg/km".  I think something similar could be done for the other question. Think about it.

**Comment by heychirag** [comment]
Glad you liked the redesign!

> The fuel type is only relevant when the user is inputing fuel efficiency/consumption. Therefore, the fuel type should be below the first question.

As a matter of fact, fuel type was below the first question before my last commit. But then Prateek suggested that fuel type would be necessary for calculating the trip cost. If you believe that it is not relevant, I will revert my last commit and raise a PR.

 > I think "US Customary" is usually called "Imperial" unit system. Could you please check this?

These two system of units are not equivalent. Check out [this](https://en.wikipedia.org/wiki/Comparison_of_the_imperial_and_US_customary_measurement_systems) wikipedia article.

The imperial system is not used by any country at present. The only countries that do not use Metric system are US, Liberia and Myanmar. According to [this](https://www.quora.com/Why-dont-Liberia-and-Myanmar-use-the-metric-system) answer on Quora, Liberia and Myanmar use Metric system on a large scale but haven't declared it to be official. This leaves us with US, which has its custom set of Units derived from historical [English units](https://en.wikipedia.org/wiki/English_units). 

I'll consider your other suggestions and raise a PR soon!

I would also like to discuss with you about fuels that are sold by weight and not by volume. Like in India, CNG/LPG is sold in Kg whereas Petrol(Gasoline) and other fuels are sold in Litres. What do you think should be done about this?

**Comment by Ceilican** [comment]
> As a matter of fact, fuel type was below the first question before my last commit. But then Prateek suggested that fuel type would be necessary for calculating the trip cost in case the user provides only CO2 emission rate. If you believe that it is not relevant, I will revert my last commit.

Ok. I see. @PrateekGupta1509 has a good point. But I am still not entirely satisfied with the solution.

Maybe we should have fuel type selection both in the CO2 emissions and in the cost panes? Internally, we could still store only one fuel type, but the UI would give the user two places where he/she could change the type.


> These two system of units are not equivalent. Check out this wikipedia article.

Interesting!! Thank you for elucidating!

> At present, the Imperial System is not used by any country.

Although it seems to be not official in the UK anymore, it is still widely used there. Check this: 
https://en.wikipedia.org/wiki/Metrication_in_the_United_Kingdom

>I would also like to discuss with you about fuels that are sold by weight and not by volume. Like in India, CNG/LPG is sold in Kg whereas Petrol(Gasoline) and other fuels are sold in Litres. What do you think should be done about this?

I will answer this question in the mailing-list...

**Pull request merged**
