### PR TITLE
safari core files

### PR DESCRIPTION
**Pull request by heychirag**
core files for Apple Safari

### CODE REVIEW

**Comment by Ceilican** [comment]
Great! Thanks!

**Comment by Ceilican** [comment]
I think "vendor" should be replaced by "browser" in the folder name.

**Comment by Ceilican** [comment]
Is there a reason why the Safari files are in "Source/vendor/safari" whereas the Chrome files are in "Source"? Are they sharing files? If not, would it make sense to move the safari files to, for instance, "Source-Safari" instead of "Source/vendor/safari"??

**Comment by heychirag** [comment]
> I think "vendor" should be replaced by "browser" in the folder name.

Okay, I'll get this done.

>Is there a reason why the Safari files are in "Source/vendor/safari" whereas the Chrome files are in "Source"? Are they sharing files? If not, would it make sense to move the safari files to, for instance, "Source-Safari" instead of "Source/vendor/safari"??

Yes, they will indeed be sharing files. But the files that can't be shared will be included in source/browser folder. Analogously, background.js from source/background will be moved to source/browser/chrome/background since its specific to chrome.

**Comment by Ceilican** [comment]
Ok. This sounds good.

**Pull request merged**
