### PR TITLE
[Enhancement] Add travel cost 

### PR DESCRIPTION
**Pull request by rohankatyal29**
I went through the open PRs and saw that a couple of things from issue  (#11)  were missing such as the ability for the user to select if the fuel cost should be calculated. 

I have created another PR with all the necessary features and commits squashed into 1 for easy reviewing. 

The extra fields are only displayed if the user wants the fuel cost to be displayed. 

The screenshots are as follows: 
screen shot 2016-03-04 at 7 02 47 pm
screen shot 2016-03-04 at 6 53 33 pm
screen shot 2016-03-04 at 6 53 28 pm

### CODE REVIEW

**Comment by Ceilican** [comment]
@rohankatyal29 :  @PrateekGupta1509 's pull request has been merged. You can implement travel cost calculation on top of that now, as we discussed.

**Comment by rohankatyal29** [comment]
@Ceilican , I am working on it

**Comment by Ceilican** [comment]
And how is it going?

**Comment by rohankatyal29** [comment]
@Ceilican , sorry for the delay. I am down with a flu. 

This PR has been updated with the following commits: 

- Travel cost support for Bing, Google and OpenStreet maps

- In the latest version of the code changing the CO2 emission value in the options page wasn't being used in the calculations (only the default value of 217 was always being used), now that has been fixed.

@PrateekGupta1509 , I have added a checkbox in the options page, but somehow the CSS which is already on the page is not letting the checkbox and label be on the same line. Can you have a look at it?

**Comment by Ceilican** [comment]
Thanks!

**Comment by Ceilican** [comment]
@goelrohan6 now that this PR has been merged, could you rebase the improvements of your PR onto the current master branch?

**Pull request merged**
