### PR TITLE
Issue #8: UI design change

### PR DESCRIPTION
**Pull request by PrateekGupta1509**
New UI Design for option.html. Key features:
- Used media query to create a responsive UI instead of loading bootstrap
- Flat UI colour
- Based on vanilla javascript

c1

### CODE REVIEW

**Comment by Ceilican** [comment]
I like it!  I would like to merge it, but it is not automatically mergeable because it has conflicts. Could you please make it automatically mergeable? (To do that, you must incorporate into your branch the recent changes that have been made in this repository's master branch.)

**Comment by Ceilican** [comment]
Also, you may remove the "Offset your carbon emissions now!" link, because it is broken. (The non-profit foundation that used to offer tree-planting is not offering it anymore.)

**Comment by Ceilican** [comment]
@rohankatyal29 @goelrohan6 @PrateekGupta1509 :

I would like to merge all your contributions. To make this easy, please do the following, in this order:

1) @PrateekGupta1509 , make this pull request automatically mergeable.

2) @rohankatyal29 , please wait for me to merge this pull request into the master branch, then rebase your changes regarding fuel costs onto the new master branch and using the new UI and resubmit your pull request for this contribution. I will then merge your pull request.

3) @goelrohan6 , please wait for me to merge the pull request that will be created by @rohankatyal29 above. Then add your contributions about the measurement unit for CO2 emissions.

Did I miss something?

**Comment by rohankatyal29** [comment]
@Ceilican , got it 

+1 for the new UI

**Comment by PrateekGupta1509** [comment]
@Ceilican Thank you, i am glad you like it. Also i have made this auto mergeable.

@rohankatyal29 Thanks!

**Comment by Ceilican** [comment]
@PrateekGupta1509, Thanks!

@rohankatyal29 , you can now rebase your pull request, as discussed above.

**Comment by rohankatyal29** [comment]
@Ceilican , will do it asap

**Comment by rohankatyal29** [comment]
I don't think we need 2 separate tabs for consumption and efficiency. They are practically the same thing (just inversed!). @PrateekGupta1509 , you are only saving the carbonEmission in the localStorage. You should save the other values as well, we need them for calculations in GoogleMapsCarbonFootprint.js. I need fuel efficiency to calculate the travel cost. I can see the need for such values being available in other files for other features as well. 

@Ceilican , what do you think?

**Comment by PrateekGupta1509** [comment]
@rohankatyal29 The 2 tabs were separate so that user could conveniently enter consumption or efficiency without doing the reciprocal himself. So from a UX point of view it makes sense.

Also i agree the you would need fuel type as well as efficiency/consumption to make travel cost estimate but there was **loop hole** in that regard because if the user directly gives CO2 emission. You might use the previously stored or default inputs for fuel type and consumption which will result in a totally incorrect calculation for travel cost.

As a solution to this i think we should store the var index_et as well which stores the type of information the user has given i.e currently 0- fuel consumption, 1- fuel efficiency, 2- CO2 emission. You can build up cases depending on these input types and estimate the travel cost in case of fuel consumption or efficiency. 

If you have some other work around to the problem i mentioned above let me know. I will make the changes to facilitate it. Or we can go with the solution i suggested.

Also @Ceilican to calculate travel cost are we supposed to take fuel rate (for which we will have to currency and cost per volumetric unit in their country ) from the user?

**Comment by Ceilican** [comment]
> I don't think we need 2 separate tabs for consumption and efficiency. They are practically the same thing (just inversed).

I agree with @PrateekGupta1509 that, from a UI point of view, it is useful to have both.
And I agree with @rohankatyal29 that, from an internal perspective, one is just the inverse of the other.

> @PrateekGupta1509 , you are only saving the carbonEmission in the localStorage. You should save the other values as well, we need them for calculations in GoogleMapsCarbonFootprint.js.

Yes. It is important to distinguish between values that are "primitive" and those that are derived/computable from the primitive values.

All primitive values should be stored, and only primitive values should be stored.

Deciding which values should be considered primitive is not as simple as it might seem.

Primitive values should be, as much as possible, independent from each other.

> Also I agree the you would need fuel type as well as efficiency/consumption to make travel cost estimate but there was loop hole in that regard because if the user directly gives CO2 emission. You might use the previously stored or default inputs for fuel type and consumption which will result in a totally incorrect calculation for travel cost.

This shows that there is a dependence between these values. Some of them can be computed based on the others. So, they shouldn't be all primitive.

When the user inputs a non-primitive value, the interface should do the necessary inverse calculations to update and store the primitive values on which the given non-primitive value depends. 

Of course, this is not always possible. For instance, assume that c is a derived value defined by c = a + b  and the stored values for a and b are, respectively, 3 and 5.  Then, if the user inputs the new value 10 for c, it is not clear how we should change a and b. Should we increase a to 5? Should we increase b to 7? There are infinitely many options in this case...  

But in the case of the dependence of CO2 emissions on fuel type and fuel consumption, the dependence is simpler, and it seems clear to me that, for example, If the user increases the CO2 emissions, the fuel type should remain the same and the fuel consumption should be increased proportionally.

> Also @Ceilican to calculate travel cost are we supposed to take fuel rate (for which we will have to take currency and cost per volumetric unit in their country/state ) from the user? if so what all currency options should we provide to the user?

We don't need to worry about currencies. We just use the symbol "$" for a generic currency, and we let the user interpret it in any way he/she wants. For example, if I am in Europe, and I write that the cost per liter is $1,50, I mean that it is 1,50 euros per liter. If I am in the US and I write $1, I mean 1 dollar per liter...

@PrateekGupta1509 , focus on implementing the interface in a way that all the needed primitive values are stored and correctly updated when the user changes values. Then @rohankatyal29 and @goelrohan6 will take care of costs and other measurement units, as explained above.

**Comment by goelrohan6** [comment]
@Ceilican therefore we can provide a fuel cost input in all the three tabs and calculate the cost accordingly then. right?

**Comment by rohankatyal29** [comment]
@PrateekGupta1509 , instead of storing the CO2Emission value can you please store the primitives and calculate the CO2Emission where ever required. Secondly, while making the changes to the UI can you please input and store the cost of fuel in $/L as well.

**Comment by PrateekGupta1509** [comment]
@rohankatyal29 For now i will add the fuel cost in all the 3 tabs and store it. Since we are only storing primitive values which will remove CO2 emission, I was also thinking of adding a function for you to use to calculated value of CO2 Emission.
For example: If CO2 emission is  212 kg/km , the function will return an 
JSON with { value:212,
unit1:'kg',unit2:'km'];
Let me know if this will be make things easier for you.

@Ceilican In the case user just enters the CO2 emission, we wont have a fuel type (because user never entered one before) to recalculate fuel efficiency. So i think we should add fuel type input as well in the tab for CO2 Emission.
Also there are a few

**Comment by PrateekGupta1509** [comment]
@Ceilican a problems that i encountered in the current implementation with primitive variables namely storing:
 FuelType, 
 FuelCost(value ,$ , liter or gallon),
 FuelConsumption(value, unit in numerator[ liter or gallon], unit in denominator[ kilometer or miles] )

Firstly, since CO2 Emission is not a primitive variable, we are not storing the units which we want for its output.
**Example**: If user enters CO2 emission in lbs we convert it  to respective fuel efficiency to store. But now we have no way of knowing that he entered the value in lbs. So we can't decide the unit for output.

**Possible solution** storing the unit as well and keeping 'gram' as default unit until user specifies some other unit i.e (kg or lbs).

**Comment by goelrohan6** [comment]
@Ceilican @PrateekGupta1509 @rohankatyal29 What I think is it is illogical to calculate cost from amount of CO2 car emits, the cost can only be calculated accurately when the user inputs his/her car efficiency, fuel rate is to be taken anyways.

So what I propose is to ask the user if he/she wants the cost to be calculated, if yes then (trigger a modal) ask his/her car fuel efficiency and fuel cost and then calculate the cost.

Now coming to the part which @PrateekGupta1509  stated regarding storage of primitive values, in my pull request #29 (@ceilican if you can review it ?) I had taken into account these factor's i.e storage of input units like lb or kg separately and then manipulating it later to display emission.

**Comment by Ceilican** [comment]
> Where can we have that discussion as github isn't really the fastest choice? Over mail or IRC or anywhere that you suggest?

That's a good idea. But I won't have time until Friday evening.  (I would prefer chatting via Skype. My username is "<firstname>.<initials of family name>"), and you know my name from the mailing-list.

Would you be available on Friday at 17:00 (Sydney time)?

In the meanwhile, I will try to think about these issues.

@goelrohan6 : I have reviewed your PR https://github.com/OiWorld/CarbonFootprintGoogleMaps/pull/29 already, and I liked it. The reason I haven't merged it is that I want it to be merged after this PR. Just be patient.

**Comment by goelrohan6** [comment]
@Ceilican @rohankatyal29 @PrateekGupta1509 we may discuss the matter on google hangouts anytime on mutual consensus for a fruitful discussion. :D

**Comment by PrateekGupta1509** [comment]
@Ceilican I am free on Friday 17:00 (Sydney time), I have already added you in the contact list and have sent you a message , let's discuss the details there. Thank you for your time :)

**Comment by Ceilican** [comment]
@rohankatyal29 @goelrohan6 What about you? Are you free on Friday 11th March 17:00 (Sydney time)?  It would be important to have everyone affected by these issues participating in the chat.

**Comment by rohankatyal29** [comment]
@Ceilican , I am available at that time

**Comment by Ceilican** [comment]
Good.

**Comment by goelrohan6** [comment]
@Ceilican i will also be present there .
Can u email me your username?

**Pull request merged**
