### PR TITLE
issue#35 resolved

### PR DESCRIPTION
**Pull request by ayush1997**
The variable carbon emission was constant, now it is taking local storage values.

### CODE REVIEW

**Comment by Ceilican** [comment]
This PR became unmergeable. Could you rebase it?

Also, it seems that the issue was solved in another PR.

**Comment by rohankatyal29** [comment]
@Ceilican , this has been taken care of in my PR. 

Sorry @ayush1997 , I didn't realise you had already raised a PR for this

**Comment by Ceilican** [comment]
Please check, and if you think that your PR's solution is better than the current solution, please comment here.

In any case, thank you! Even if this PR doesn't get merged, you should still mention it, and the bugs it solved, in your GSoC proposal.

**Comment by rohankatyal29** [comment]
It's the same solution, someone had deleted a variable assignment which had to be added again

**Comment by Ceilican** [comment]
Yes. It is unfortunate that two people solved the same problem. @ayush1997 solved it first, but I couldn't merge it before, because @ayush1997 's original PR also contained the implementation of a feature, which shouldn't be merged before @rohankatyal29 's and @goelrohan6 's PRs. Adding that feature at this point would have broken the workflow that had been established to solve the clash between the PRs of @PrateekGupta1509 , @rohankatyal29 and @goelrohan6 .

**Comment by ayush1997** [comment]
Sir,
I will again push the PR to solve issue#3 so that it is mergable.

Thank You
Ayush

**Comment by Ceilican** [comment]
Closing, according to our discussion.

**Pull request closed without merging**
